/* ENV - Local */

const ConfigKeyLocal = {
  HASURA_GRAPHQL_JWT_SECRET: process.env.HASURA_GRAPHQL_JWT_SECRET,
  HASURA_GRAPHQL_DATABASE_URL: process.env.HASURA_GRAPHQL_DATABASE_URL_LOCAL,
  AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID_LOCAL,
  AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY_LOCAL,
  AWS_BUCKET_NAME: process.env.AWS_BUCKET_NAME_LOCAL,
  DISCORD_WEBHOOK_ID: process.env.DISCORD_WEBHOOK_ID,
  DISCORD_WEBHOOK_TOKEN: process.env.DISCORD_WEBHOOK_TOKEN,
  DISCORD_WEBHOOK_USERNAME: process.env.DISCORD_WEBHOOK_USERNAME_LOCAL,
  APP_PORT: process.env.APP_PORT_DEV
};

export default ConfigKeyLocal;
