/* ENV - Development */

const ConfigKeyDev = {
  HASURA_GRAPHQL_JWT_SECRET: process.env.HASURA_GRAPHQL_JWT_SECRET,
  HASURA_GRAPHQL_DATABASE_URL: process.env.HASURA_GRAPHQL_DATABASE_URL_DEV,
  AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID_DEV,
  AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY_DEV,
  AWS_BUCKET_NAME: process.env.AWS_BUCKET_NAME_DEV,
  DISCORD_WEBHOOK_ID: process.env.DISCORD_WEBHOOK_ID,
  DISCORD_WEBHOOK_TOKEN: process.env.DISCORD_WEBHOOK_TOKEN,
  DISCORD_WEBHOOK_USERNAME: process.env.DISCORD_WEBHOOK_USERNAME_DEV,
  APP_PORT: process.env.APP_PORT_DEV
};

export default ConfigKeyDev;
